dependencies = []
description = "Terraform Provider allowing to control resources created on Scalingo"
destination_server = []
flags = ["devops", "sdk", "tools"]
languages = ["go"]
owner = "team-infrastructure-services@scalingo.com"
team = "IST"
version = "2.7.0"
